on:
  push:
    tags:
      - "*"

jobs:
  release:
    # Temporary solution as the current implementation runs out of disk space on the github hosted runners. #1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Install dependencies
        run: go mod tidy

      - name: Extract files and release them.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run .
